<?php
return [
	'allowed_mime_types' => [
		// Image
		'image/gif',
		'image/jpeg',
		'image/png',

		// Audio
		'audio/mpeg',
		'audio/x-ms-wmv',
		'audio/webm',

		// Video
		'video/msvideo',
		'video/avi',
		'video/x-msvideo',
		'video/mpeg',
		'video/x-ms-wmv',
		'video/quicktime',
		'video/3gpp',
		'video/mp4',
		'video/x-flv',
		'video/webm',

		// Documents
		'text/plain',
		'application/pdf',
		'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
		'application/vnd.ms-powerpointtd',
		'application/vnd.openxmlformats-officedocument.presentationml.presentation',
		'application/rtf',
		'application/rdf',
		'application/rdf+xml',
		'application/vnd.ms-excel',
		'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
		'application/zip',
		'application/x-compressed-zip',
		'application/msword',
		'application/doc',
		'application/x-doc',
		'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		"application/msword",
		"application/ms-word",
		"application/ms-excel",
		"application/msexcel",
		"application/vnd.ms-word",
		"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		"application/vnd.openxmlformats-officedocument.wordprocessingml.template",
		"application/msexcel",
		"application/x-msexcel",
		"application/x-ms-excel",
		"application/x-excel",
		"application/x-dos_ms_excel",
		"application/xls",
		"application/x-xls",
		"application/vnd.ms-word.document.macroEnabled.12",
		"application/vnd.ms-word.template.macroEnabled.12",
		"application/vnd.ms-excel",
		"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
		"application/vnd.openxmlformats-officedocument.spreadsheetml.template",
		"application/vnd.ms-excel.sheet.macroEnabled.12",
		"application/vnd.ms-excel.template.macroEnabled.12",
		"application/vnd.ms-excel.addin.macroEnabled.12",
		"application/vnd.ms-excel.sheet.binary.macroEnabled.12",
		"application/vnd.ms-powerpoint",
		"application/vnd.openxmlformats-officedocument.presentationml.presentation",
		"application/vnd.openxmlformats-officedocument.presentationml.template",
		"application/vnd.openxmlformats-officedocument.presentationml.slideshow",
		"application/vnd.ms-powerpoint.addin.macroEnabled.12",
		"application/vnd.ms-powerpoint.presentation.macroEnabled.12",
		"application/vnd.ms-powerpoint.template.macroEnabled.12",
		"application/vnd.ms-powerpoint.slideshow.macroEnabled.12",
		"",

	],

	'forbidden_extensions' => ['html','php','htm','exe','dmg','bat','sh','php5','asp','js','pkg','bin','pl','py','rb','cmd','bat','com','php3','aspx','aspm','tpl','xps'],
	'max_size' => [
		'images' => (10 * 1024 * 1024),
		'videos' => (100 * 1024 * 1024),
		'generic' => (5 * 1024 * 1024),
	],
];